#!/bin/bash
# Idea by br0ns (https://github.com/br0ns/bootstrap)
# Modified to bootstrap-fedora repo
#
# Torsten Juul-Jensen
# February 7, 2020

# Direct URL to bootstrap master archive on github
BOOTSTRAP_ARCHIVE="https://github.com/tjuuljensen/bootstrap-fedora/archive/master.zip"

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" #set the variable to the place where script is loaded from

# Fail on any error
set -e

# If this file does not exist it's probably because we're bootstrapping a fresh
# system.  So we download the Git repository and bootstrap from there
if [ ! -e "$SCRIPTDIR/fedora-lib.sh" ] ; then
    # Install required packages
    REQUIREDPACKAGES=("unzip" "wget")
    for i in ${!REQUIREDPACKAGES[@]};
    do
      rpm -q --quiet ${REQUIREDPACKAGES[$i]}  || dnf install -y ${REQUIREDPACKAGES[$i]}
    done

    TEMPDIR="$(mktemp -d /tmp/bootstrap.XXXXXXXXXX)"
    echo -e "Downloading \x1b[32m$BOOTSTRAP_ARCHIVE\x1b[m => \x1b[32m$TEMPDIR/\x1b[m"
    cd $TEMPDIR
    wget "$BOOTSTRAP_ARCHIVE"
    unzip master.zip
    DIR="$(realpath "$TEMPDIR/bootstrap-fedora-master/")"
fi

# Start the installation of the default preset
./bootstrap-loader.sh --include fedora-lib.sh --preset default.preset
